# Creating some books
Book.create(title: "The Secret Garden", author: "Frances Hodgson Burnett", description: "When orphaned Mary Lennox comes to live at her uncle's great house on the Yorkshire Moors, she finds it full of secrets. The mansion has nearly one hundred rooms, and her uncle keeps himself locked up. And at night, she hears the sound of crying down one of the long corridors.", image_url: "https://m.media-amazon.com/images/I/61elZCuOZ0L._SL350_.jpg")

Book.create(title: "Harry Potter and the Sorcerer's Stone", author: "JK Rowling", description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!", image_url: "https://m.media-amazon.com/images/I/413lxIe20jL.jpg")

Book.create(title: "Harry Potter and the Chamber of Secrets", author: "JK Rowling", description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby's sinister predictions seem to be coming true.", image_url: "https://m.media-amazon.com/images/I/51TA3VfN8RL.jpg")

Book.create(title: "Harry Potter and the Prizoner of Azkaban", author: "JK Rowling", description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves... But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss...", image_url: "https://m.media-amazon.com/images/I/51Dfqo6jR5L.jpg")

Book.create(title: "Harry Potter and the Goblet of Fire", author: "JK Rowling", description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!", image_url: "https://m.media-amazon.com/images/I/51Vjb2qJwzL.jpg")

Book.create(title: "Harry Potter and the Order of the Phoenix", author: "JK Rowling", description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time ...", image_url: "https://m.media-amazon.com/images/I/51-SI2+aQ2L.jpg")

Book.create(title: "Harry Potter and the Half Blood Prince", author: "JK Rowling", description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny...", image_url: "https://m.media-amazon.com/images/I/51myHyjJsyL.jpg")

Book.create(title: "Harry Potter and the Deathly Hallows", author: "JK Rowling", description: "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy...", image_url: "https://m.media-amazon.com/images/I/511DhzIj4cL.jpg")

Book.create(title: "The Hobbit", author: "JRR Tolkien", description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.", image_url: "https://m.media-amazon.com/images/I/5187PQgDScL.jpg")

Book.create(title: "The Fellowship of the Ring", author: "JRR Tolkien", description: "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.", image_url: "https://m.media-amazon.com/images/I/41kUPvqlguL.jpg")

Book.create(title: "The Two Towers", author: "JRR Tolkien", description: "Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go. ", image_url: "https://m.media-amazon.com/images/I/4123zOAwAgL.jpg")

Book.create(title: "The Return of the King", author: "JRR Tolkien", description: "As the Shadow of Mordor grows across the land, the Companions of the Ring have become involved in separate adventures. Aragorn, revealed as the hidden heir of the ancient Kings of the West, has joined with the Riders of Rohan against the forces of Isengard, and takes part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escape into Fangorn Forest and there encounter the Ents. Gandalf has miraculously returned and defeated the evil wizard, Saruman. Sam has left his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive—now in the foul hands of the Orcs. And all the while the armies of the Dark Lord are massing as the One Ring draws ever nearer to the Cracks of Doom.", image_url: "https://m.media-amazon.com/images/I/41KGl2FqeAL.jpg")




# Creating some reviews
Review.create(title: "The Secret Garden: A Trip Down Memory Lane", content: "The Secret Garden is one of my favorite books, and was one of the first chapter books I read. I remember taking turns reading with my Mother, and Mary's journey and adventures with her cousin captivated me and lead to a lifelong love of historical fiction novels.", book_id: 1)
# Comment.create(content:"I also read this book with my mom :)", user_id: 3, review_id: 1)